### ISSUE TITLE
Dependency lock on patch level makes npm run dev fail

### ISSUE THREAD

**Issue by tehandyb** [pirelenito/generator-react-webpack-component#4]
I tried using npm run dev recently and saw that it was failing. This is the error: 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE
npm ERR! react-loading-simple@1.0.0 dev: `webpack-dev-server --inline --hot`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the react-loading-simple@1.0.0 dev script 'webpack-dev-server --inline --hot'.
npm ERR! This is most likely a problem with the react-loading-simple package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-loading-simple
npm ERR! There is likely additional logging output above.

I traced it back and found that the addition of these two lines in package.json caused the issue from the commit "locks dependencies on patch level": 
    "webpack": "~1.5.3",
    "webpack-dev-server": "~1.7.0"

I changed the ~ back to ^ and npm run dev worked fine. Not sure what the issue would be, I checked to see if my global install of webpack was breaking this, but after I removed the global installs the issue was the same.

**Comment by pirelenito** [comment]
To fix this, I've updated all the dependencies of the generated project with 8303cb5f039be3b906cfec5de091e6a120543472.

Thanks @tehandyb

**Comment by tehandyb** [comment]
Nice, thanks!
